/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treetank_pagelayer_NativeCompression */

#ifndef _Included_org_treetank_pagelayer_NativeCompression
#define _Included_org_treetank_pagelayer_NativeCompression
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_treetank_pagelayer_NativeCompression
 * Method:    compress
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_treetank_pagelayer_NativeCompression_compress
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_treetank_pagelayer_NativeCompression
 * Method:    decompress
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_treetank_pagelayer_NativeCompression_decompress
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
