/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treetank_pagelayer_NativeTreeTank */

#ifndef _Included_org_treetank_pagelayer_NativeTreeTank
#define _Included_org_treetank_pagelayer_NativeTreeTank
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: queue */
/*
 * Class:     org_treetank_pagelayer_NativeTreeTank
 * Method:    write
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_treetank_pagelayer_NativeTreeTank_write
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     org_treetank_pagelayer_NativeTreeTank
 * Method:    read
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_treetank_pagelayer_NativeTreeTank_read
  (JNIEnv *, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
