/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treetank_pagelayer_NativeTreeTank */

#ifndef _Included_org_treetank_pagelayer_NativeTreeTank
#define _Included_org_treetank_pagelayer_NativeTreeTank
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: queue */
/*
 * Class:     org_treetank_pagelayer_NativeTreeTank
 * Method:    write
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_treetank_pagelayer_NativeTreeTank_write
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     org_treetank_pagelayer_NativeTreeTank
 * Method:    read
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_treetank_pagelayer_NativeTreeTank_read
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
