/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treetank_pagelayer_CryptoNativeImpl */

#ifndef _Included_org_treetank_pagelayer_CryptoNativeImpl
#define _Included_org_treetank_pagelayer_CryptoNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef org_treetank_pagelayer_CryptoNativeImpl_CORE_COUNT
#define org_treetank_pagelayer_CryptoNativeImpl_CORE_COUNT 15L
#undef org_treetank_pagelayer_CryptoNativeImpl_ERROR
#define org_treetank_pagelayer_CryptoNativeImpl_ERROR 0L
#undef org_treetank_pagelayer_CryptoNativeImpl_COMMAND_WRITE
#define org_treetank_pagelayer_CryptoNativeImpl_COMMAND_WRITE 1L
#undef org_treetank_pagelayer_CryptoNativeImpl_COMMAND_READ
#define org_treetank_pagelayer_CryptoNativeImpl_COMMAND_READ 2L
/* Inaccessible static: coreQueue */
/*
 * Class:     org_treetank_pagelayer_CryptoNativeImpl
 * Method:    syscall
 * Signature: (BBSLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_treetank_pagelayer_CryptoNativeImpl_syscall
  (JNIEnv *, jobject, jbyte, jbyte, jshort, jobject);

#ifdef __cplusplus
}
#endif
#endif
