/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_treetank_pagelayer_CryptoNativeImpl */

#ifndef _Included_org_treetank_pagelayer_CryptoNativeImpl
#define _Included_org_treetank_pagelayer_CryptoNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: coreQueue */
/*
 * Class:     org_treetank_pagelayer_CryptoNativeImpl
 * Method:    syscall
 * Signature: (BBSLjava/nio/ByteBuffer;)S
 */
JNIEXPORT jshort JNICALL Java_org_treetank_pagelayer_CryptoNativeImpl_syscall
  (JNIEnv *, jobject, jbyte, jbyte, jshort, jobject);

#ifdef __cplusplus
}
#endif
#endif
